---
# sample trendbox.yaml
language: node_js

sandbox:
  vault:
    group: DMTRMONAKHOV_SANDBOX_GROUP
env: SANDBOX_PRIVILEGED_CONTAINER=true REGISTRY=registry.yandex.net USER=dmtrmonakhov IMG_NAME=qemu-qa-kit

install: npm install -g parallel
before_script: sudo service docker start
script:
  - mkdir work report
  - lscpu
  - lsmod
  - dmesg -k
  - sudo modprobe kvm || /bin/true
  - sudo modprobe kvm-intel || /bin/true
  - sudo mknod /dev/kvm c 10 232 || /bin/true
  - sudo ls -lh /dev
  - docker build --network=host --rm --no-cache -t $IMG_NAME -f Dockerfile . | tee work/log.build
  - docker tag $IMG_NAME $REGISTRY/$USER/$IMG_NAME:latest
  # Basic test
  - cat tests/list.txt | grep -v '#' | parallel sudo bash -xe
  # Push
  - docker login -u $USER -p $REGISTRY_OAUTH $REGISTRY
  - docker push $REGISTRY/$USER/$IMG_NAME:latest
  - docker save $REGISTRY/$USER/$IMG_NAME:latest -o image.tar.gz
after_script:
  - sudo service docker stop
  - find work -type f -name 'log.*' | xargs -n1 cp -t ./report
  - trendbox publish-report ./report
  - trendbox publish-report ./report
  - trendbox publish-report ./report
  - trendbox publish-resource image.tar.gz --type DOCKER_IMAGE_SOURCE_RESOURCE --description "docker image $REGISTRY/$USER/$IMG_NAME:latest" --attr docker_img_name="$REGISTRY/$USER/$IMG_NAME:latest" --ttl 30

