#!/bin/bash

VOL=${PWD}/volume
DIR=$(dirname $0)
IMAGE=qemu-qa-kit
RUN_ID=$(date +%Y%m%d%H%M)

_fail()
{
    echo $1
    exit 1
}

_usage()
{
    [ -z "$1" ] || echo $1
    echo "Usage: $0 "
    echo "	-W: mount DIR inside container at /qemu-qa-kit/volume, default: $VOL"
    echo "	-p: port forward for docker, example [2222:22] forward 22-container's port to host:2222"
    echo "	-it: Attack terminal to docker container (manual/maintenance mode)"
    echo "	--job: Directory with batch job configuration, see $DIR/examples/batch_job"
    echo "	-N: docker image to use, default $IMAGE"
    echo "	--docker-opts: Extra docker options"
    echo "	--: delimiter, pass all options to qemu-qa-kit-run.sh"
    exit 1
}

OPTS=""
while (( $# >= 1 )); do
    case "$1" in
	-N) shift
	     IMAGE=$1
	     ;;
	-W) shift
	     VOL=$1
	     ;;
	-p) shift
	    OPTS="$OPTS -p $1"
	    ;;
	-it)
	    OPTS="$OPTS -it"
	    ;;
	--docker-opts) shift
		       OPTS="$OPTS $1"
		       ;;
	--job) shift
	    JOB=$1
	    kit_opt="$kit_opt --job /qemu-qa-kit/volume/job -G"
	    ;;
	--)
	    shift
	    break
	    ;;
	*)
	    echo 1>&2 "Invalid option: \"$1\""
	    _usage
	    ;;
	-h|--help)
	    _usage
	    ;;
    esac
    shift
done

[ -d "$VOL" ] || _usage "Volume directory: $VOL not found"
if [ ! -z "$JOB" ];then
    [ -d "$JOB" ] || _usage "Job directory: $JOB not found"
fi


docker run --rm --device /dev/kvm:/dev/kvm \
       -v $(realpath $VOL):/qemu-qa-kit/volume \
       -v $(realpath $JOB):/qemu-qa-kit/volume/job \
       $OPTS $IMAGE \
       qemu-qa-kit-run.sh $kit_opt --run-id $RUN_ID $@

code=$?
test $code -eq 0 || echo "ERROR: script fail with: $code"

LOGFILE="$VOL/logs/log.${RUN_ID}"
RESFILE="$VOL/results-${RUN_ID}.tar.xz"
echo "Log file: $LOGFILE"
echo "Results : $RESFILE"

exit $code
